import type { Metadata } from "next"; 
import { Noto_Sans_JP } from "next/font/google"; 
import "./globals.css"; 
import { cn } from "@/lib/utils";

const fontNotoSansJP = Noto_Sans_JP({ subsets: ["latin"] }); 

export const metadata: Metadata = { 
  title: "kimidake-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) { 
  return (
    <html lang="ja"> 
      <body className={cn("bg-background antialias min-h-screen", fontNotoSansJP.className, "text-black")}> 

        {children} {/* 子要素を表示 */}
      </body>
    </html>
  );
}